services:
    zookeeper:
        container_name: zookeeper
        image: zookeeper
        restart: always
        ports:
           - 2181:2181
        networks:
            kafka_net:
                ipv4_address: 172.20.0.2

    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka
        restart: always
        ports:
           - 9092:9092
        networks:
            kafka_net:
                ipv4_address: 172.20.0.3  
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
networks:
    kafka_net:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16